sudo: required
services:
  - docker

before_install:
  - docker build -t timzehr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t timzehr/react-test npm test -- --coverage

after_success:
  - docker build -t timzehr/multi-client ./client
  - docker build -t timzehr/multi-nginx ./nginx
  - docker build -t timzehr/multi-server ./server
  - docker build -t timzehr/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push timzehr/multi-client
  - docker push timzehr/multi-nginx
  - docker push timzehr/multi-server
  - docker push timzehr/multi-worker
